# Generated by Django 5.1.4 on 2024-12-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_message_post_content_remove_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
